### ISSUE TITLE
Highlight arrow of block which will be executed

### ISSUE THREAD

**Issue by matthewfarrellex** [Vector35/debugger#295] opened 2022-10-22 20:45 UTC
Currently there is no indicator for which block will be executed. It is a must have thing I guess. In IDA, the path that will be executed is blinks.

![arrow](https://user-images.githubusercontent.com/98181390/197361582-ff337fc2-57c3-4c66-b25b-c110642800f8.png)

**Comment by xusheng6** [comment] 2022-11-01 09:04
Duplicate of #83

**Closed as completed by xusheng6** 2022-11-01 09:04 UTC
