### ISSUE TITLE
Debug multiple files in the same session

### ISSUE THREAD

**Issue by VelocityRa** [Vector35/debugger#64] opened 2021-01-06 11:10 UTC
The most straightforward use case is for debugging the main executable + the `.dll`s it depends on.
So that you're able to ie. step inside a win32 API call ([1]) and see it all labeled properly instead of the 'raw' fallback view, which is currently extremely limited ([2]).

Not sure about scope, would Binja's core would need major changes for this too?

---
**[1]**: Or just any `.dll` of course, many ie. games are spread out in multiple `.dll`s.
**[2]**: For example: 1) it doesn't disassemble instructions 2) can't scroll it 3) can't increase the number of lines it displays.

**Comment by xusheng6** [comment] 2022-05-03 09:23
Duplicate of https://github.com/Vector35/debugger/issues/63

**Closed by xusheng6** 2022-05-03 09:23 UTC
