### ISSUE TITLE
Binary Ninja crashed when debugging

### ISSUE THREAD

**Issue by stellarix** [Vector35/debugger#506] opened 2023-08-26 12:56 UTC
Binary ninja version: 3.5.4480-dev Personal
Platform: Linux

Steps to reproduce:
1. Load a binary
2. Click debugger -> Launch until the program finish -> Click on Symbols tab then BN will Segmentation fault

Also tested on BN version 3.5.4468-dev, 3.5.4478-dev.

[gdb-log.txt](https://github.com/Vector35/debugger/files/12445334/gdb-log.txt)
[logfile.txt](https://github.com/Vector35/debugger/files/12445337/logfile.txt)

This only happens on the dev branch.

**Comment by xusheng6** [comment] 2023-08-28 06:18
This first happens in dev version 4400, very likely caused by [a693c795f73686eb8901eeb70e252b9ca796049d](https://github.com/Vector35/binaryninja-api/commit/a693c795f73686eb8901eeb70e252b9ca796049d)

**Comment by bpotchik** [comment] 2023-08-29 18:54
Fixed in `3.5.4482-dev`.

**Closed as completed by bpotchik** 2023-08-29 18:54 UTC
