### ISSUE TITLE
Default register name column width is not wide enough for register names

### ISSUE THREAD

**Issue by 0cyn** [Vector35/debugger#269] opened 2022-10-19 20:04 UTC
![image](https://user-images.githubusercontent.com/55725881/196791592-a3ef94f4-fec9-4aa9-9f55-c138f1d515a0.png)

**Comment by op2786** [comment] 2022-11-10 08:15
I can not reproduce this, probably fixed by c49e4ee6dc3c5b6eb1c108bca85b6e28afeff673?

**Comment by xusheng6** [comment] 2022-11-15 02:31
@op2786 This can be reproduced by the following steps:

1. Enable "hide unused registers" (which is the default)
2. Launch an x86 or x64 executable
3. Disable "hide unused registers"
4. Observe the width of the names column is too small and it clips long register names like `rflags`

This should be a relatively easy fix, since we are just missing a column width update when the user toggle the "hide unused registers". Add an update to it should fix the problem.

Also iirc there is a similar problem when we filter registers. Suppose a filter is applied and it hides rflags, then if we change the filter or disable it, then the rflags will show up. However, the column width will not change, and it clips the register name. This could be fixed in a similar way as well.

**Closed as completed** 2022-11-22 03:49 UTC
Labels: good first issue, Effort: Trivial, Impact: Low, UI
