### ISSUE TITLE
LLDB Broken on i386 binary (vortex13)

### ISSUE THREAD

**Issue by Taldgan** [Vector35/debugger#522] opened 2023-11-18 22:27 UTC
- On trying to launch the debugger, it is 'unable to resolve breakpoints to any actual locations'
- When trying to use the compiled/supplied lldb binary directly, it says the file 'doesn't contain any 'host' platform architectures: x86_64, i386'

To be clear - it seems that binary ninja actually succeeds in launching the binary, but fails to hit any breakpoints since they're not resolved. 

Binary is an i386 binary compiled for Ubuntu 22.04.

```sh
vortex13@gibson:~$ file /vortex/vortex13
/vortex/vortex13: setuid ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=d6cb3c25161f1629dafb6196afeea58b6fb843c3, for GNU/Linux 3.2.0, not stripped
```

**Comment by xusheng6** [comment] 2023-11-23 09:50
Duplicate of https://github.com/Vector35/debugger/issues/499

**Closed as completed by xusheng6** 2023-11-23 09:50 UTC
