### ISSUE TITLE
Windows Kernel Debugger should display if a cond. branch is taken or not

### ISSUE THREAD

**Issue by 0xFDFDFDFD** [Vector35/debugger#595] opened 2024-07-17 09:03 UTC
It would be nice to see if a conditional branch will be taken or not in the Windows Kernel Debugger. Similar like windbg does it.
Because currently you have to search the flag in the registers to see if a jump will be taken or not.

Windbg:
![Screenshot_20240717_100146](https://github.com/user-attachments/assets/fcc972db-8a24-443a-bcb5-f4abf76cd81e)

Binary Ninja:
![Screenshot_20240717_095256](https://github.com/user-attachments/assets/b652e8c9-c3d3-4b42-a7f9-925a4b2dca9a)

**Comment by xusheng6** [comment] 2024-07-18 06:03
Duplicate of #83

**Closed as completed by xusheng6** 2024-07-18 06:03 UTC
